kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- elasticsearch-ilm-policies.yaml
- elasticsearch-index-bootstraps.yaml
- elasticsearch-index-templates.yaml
- enrichment-cache.yaml
- https://gitlab.corp.pingidentity.com/ping-cloud-private-tenant/ping-cloud-dashboards/Kibana
- logstash-search-templates.yaml
- kibana-alerts.yaml