kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: prometheus

resources:
- namespace.yaml
- grafana.yaml
- prometheus.yaml
- prometheus-job-exporter.yaml
- alertmanager.yaml
- https://github.com/Rapiki-ping/ping-cloud-dashboards/Grafana?ref=main
#- https://gitlab.corp.pingidentity.com/ping-cloud-private-tenant/ping-cloud-dashboards/Grafana

configMapGenerator:
- name: prometheus-environment-variables
  envs:
    - env_vars

- name: prom-alerts
  files:
   - default-rule.yml